/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./../src/components/app/app.vue')['default']
    AppLoading: typeof import('./../src/components/app/app-loading.vue')['default']
    AppProvider: typeof import('./../src/components/app/app-provider.vue')['default']
    AvatarUpload: typeof import('./../src/components/upload/avatar-upload.vue')['default']
    CrudCard: typeof import('./../src/components/crud/crud-card.vue')['default']
    CrudDialog: typeof import('./../src/components/crud/crud-dialog.vue')['default']
    CrudPageForm: typeof import('./../src/components/crud/crud-page-form.vue')['default']
    CrudTable: typeof import('./../src/components/crud/crud-table.vue')['default']
    CrudTableQuery: typeof import('./../src/components/crud/crud-table-query.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    LayoutAdmin: typeof import('./../src/components/layout/layout-admin.vue')['default']
    LayoutAdminAside: typeof import('./../src/components/layout/layout-admin-aside.vue')['default']
    LayoutAdminBreadcrumb: typeof import('./../src/components/layout/layout-admin-breadcrumb.vue')['default']
    LayoutAdminCopyright: typeof import('./../src/components/layout/layout-admin-copyright.vue')['default']
    LayoutAdminFooter: typeof import('./../src/components/layout/layout-admin-footer.vue')['default']
    LayoutAdminHeader: typeof import('./../src/components/layout/layout-admin-header.vue')['default']
    LayoutAdminLogo: typeof import('./../src/components/layout/layout-admin-logo.vue')['default']
    LayoutAdminMain: typeof import('./../src/components/layout/layout-admin-main.vue')['default']
    LayoutAdminMenu: typeof import('./../src/components/layout/menu/layout-admin-menu.vue')['default']
    LayoutAdminMenuItem: typeof import('./../src/components/layout/menu/layout-admin-menu-item.vue')['default']
    LayoutAdminTab: typeof import('./../src/components/layout/layout-admin-tab.vue')['default']
    LayoutMenuCollapse: typeof import('./../src/components/layout/menu/layout-menu-collapse.vue')['default']
    LayoutPage: typeof import('./../src/components/layout/layout-page.vue')['default']
    LayoutToolbar: typeof import('./../src/components/layout/toolbar/layout-toolbar.vue')['default']
    LayoutToolbarAvatar: typeof import('./../src/components/layout/toolbar/layout-toolbar-avatar.vue')['default']
    LayoutToolbarColorScheme: typeof import('./../src/components/layout/toolbar/layout-toolbar-color-scheme.vue')['default']
    LayoutToolbarFullscreen: typeof import('./../src/components/layout/toolbar/layout-toolbar-fullscreen.vue')['default']
    LayoutToolbarLanguage: typeof import('./../src/components/layout/toolbar/layout-toolbar-language.vue')['default']
    LayoutToolbarMobileMenu: typeof import('./../src/components/layout/toolbar/layout-toolbar-mobile-menu.vue')['default']
    LayoutToolbarNotification: typeof import('./../src/components/layout/toolbar/layout-toolbar-notification.vue')['default']
    LayoutToolbarRefresh: typeof import('./../src/components/layout/toolbar/layout-toolbar-refresh.vue')['default']
    LayoutToolbarSetting: typeof import('./../src/components/layout/toolbar/layout-toolbar-setting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/svg-icon/svg-icon.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
