/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarUpload: typeof import('./../src/components/upload/avatar-upload.vue')['default']
    CrudCard: typeof import('./../src/components/crud/crud-card.vue')['default']
    CrudDialog: typeof import('./../src/components/crud/crud-dialog.vue')['default']
    CrudPageForm: typeof import('./../src/components/crud/crud-page-form.vue')['default']
    CrudTable: typeof import('./../src/components/crud/crud-table.vue')['default']
    CrudTableQuery: typeof import('./../src/components/crud/crud-table-query.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownMenuMenu: typeof import('element-plus/es')['ElDropdownMenuMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/svg-icon.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
