/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarUpload: typeof import('./upload/avatar-upload.vue')['default']
    CrudCard: typeof import('./crud/crud-card.vue')['default']
    CrudDialog: typeof import('./crud/crud-dialog.vue')['default']
    CrudPageForm: typeof import('./crud/crud-page-form.vue')['default']
    CrudTable: typeof import('./crud/crud-table.vue')['default']
    CrudTableQuery: typeof import('./crud/crud-table-query.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./svg-icon.vue')['default']
  }
}
